---
title: "Win Ratio Integrated (Composite Outcome with Added Covariates)"
author: "Scott Zuo"
output: 
    html_document:
      toc: TRUE
      toc_float: true
      theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(MASS)
library(nnet)
library(VGAM)
start_time <- Sys.time()
```






## Setting outcome levels

```{r}

#vector of outcomes as a factor with ordered levels
outcomes_3lvl <- factor(c("first", "second", "third"), 
                   levels = c("first", "second", "third"), 
                   ordered = TRUE)

#Order: first < second < third, the larger the better

inv_logit <- function(logit) exp(logit) / (1 + exp(logit))
```


## Define Variables

```{r}

re_count <- 15
step_size <- 20
#true_wr <- numeric(re_count)

empirical_var_Ori <- numeric(re_count)
empirical_var_IPS <- numeric(re_count)
empirical_var_OW <- numeric(re_count)
empirical_var_DR <- numeric(re_count)
empirical_var_DROW <- numeric(re_count)


avg_bias_Ori <- numeric(re_count)
avg_bias_IPS <- numeric(re_count)
avg_bias_OW <- numeric(re_count)
avg_bias_DR <- numeric(re_count)
avg_bias_DROW <- numeric(re_count)

mse_Ori <- numeric(re_count)
mse_IPS <- numeric(re_count)
mse_OW <- numeric(re_count)
mse_DR <- numeric(re_count)
mse_DROW <- numeric(re_count)
```



## Different Estimators 


```{r, warning=FALSE}

set.seed(1)

trt_eff1 <- 1
trt_eff2 <- 0.5
bi_trt1 <- c(0.1,0.1,0.1,0.1,0.1,0.1)
bi_ctrl1 <- c(0.1,0.1,0.1,0.1,0.1,0.1)
bi_trt2 <- c(0.05,0.05,0.05,0.05,0.05,0.05)
bi_ctrl2 <- c(0.05,0.05,0.05,0.05,0.05,0.05)
b01 <- 1
b02 <- 0.05





for (count_temp in 1:re_count){

n_count <- count_temp*step_size


###########################################

sim_num <- 100
WR_sim_trueWR <- numeric(sim_num)

WR_sim_comp <- numeric(sim_num)
bias_Ori <- numeric(sim_num)

WR_sim_comp_IPS <- numeric(sim_num)
bias_IPS <- numeric(sim_num)

WR_sim_comp_OW <- numeric(sim_num)
bias_OW <- numeric(sim_num)

WR_sim_comp_DR <- numeric(sim_num)
bias_DR <- numeric(sim_num)

WR_sim_comp_DROW <- numeric(sim_num)
bias_DROW <- numeric(sim_num)



#################Simulation ####################


for (sim_count in 1:sim_num){
  
# covariates
x1_trt <- rnorm(n_count, mean = 1, sd = 0.3)
x1_ctrl <- rnorm(n_count, mean = 1, sd = 0.3)
x2_trt <- rnorm(n_count, mean = 1, sd = 0.1)
x2_ctrl <- rnorm(n_count, mean = 1, sd = 0.1)

x3_trt <- rnorm(n_count, mean = 0.9, sd = 0.3)
x3_ctrl <- rnorm(n_count, mean = 0.9, sd = 0.3)
x4_trt <- rnorm(n_count, mean = 0.9, sd = 0.1)
x4_ctrl <- rnorm(n_count, mean = 0.9, sd = 0.1)

x5_trt <- rnorm(n_count, mean = 0.8, sd = 0.3)
x5_ctrl <- rnorm(n_count, mean = 0.8, sd = 0.3)
x6_trt <- rnorm(n_count, mean = 0.8, sd = 0.1)
x6_ctrl <- rnorm(n_count, mean = 0.8, sd = 0.1)

trt_cov <- data.frame(x1_trt, x2_trt, x3_trt, x4_trt, x5_trt, x6_trt)
ctrl_cov <- data.frame(x1_ctrl, x2_ctrl, x3_ctrl, x4_ctrl, x5_ctrl, x6_ctrl)

# trt outcome column 1

logodds1_trt1 <- b01 + as.matrix(trt_cov) %*% as.matrix(bi_trt1) + trt_eff1
logodds2_trt1 <- b02 + as.matrix(trt_cov) %*% as.matrix(bi_trt1) + trt_eff1


# trt outcome column 2

logodds1_trt2 <- b01 + as.matrix(trt_cov) %*% as.matrix(bi_trt2) + trt_eff2
logodds2_trt2 <- b02 + as.matrix(trt_cov) %*% as.matrix(bi_trt2) + trt_eff2

## Probability trt column 1

prob_2to3_trt1 <- inv_logit(logodds1_trt1)
prob_3_trt1 <- inv_logit(logodds2_trt1)
prob_1_trt1 <- 1 - prob_2to3_trt1
prob_2_trt1 <- prob_2to3_trt1 - prob_3_trt1

## Probability trt column 2

prob_2to3_trt2 <- inv_logit(logodds1_trt2)
prob_3_trt2 <- inv_logit(logodds2_trt2)
prob_1_trt2 <- 1 - prob_2to3_trt2
prob_2_trt2 <- prob_2to3_trt2 - prob_3_trt2





# ctrl outcome column 1

logodds1_ctrl1 <- b01 + as.matrix(ctrl_cov) %*% as.matrix(bi_ctrl1)
logodds2_ctrl1 <- b02 + as.matrix(ctrl_cov) %*% as.matrix(bi_ctrl1)

# ctrl outcome column 2

logodds1_ctrl2 <- b01 + as.matrix(ctrl_cov) %*% as.matrix(bi_ctrl2)
logodds2_ctrl2 <- b02 + as.matrix(ctrl_cov) %*% as.matrix(bi_ctrl2)

## Probability ctrl column 1

prob_2to3_ctrl1 <- inv_logit(logodds1_ctrl1)
prob_3_ctrl1 <- inv_logit(logodds2_ctrl1)
prob_1_ctrl1 <- 1 - prob_2to3_ctrl1
prob_2_ctrl1 <- prob_2to3_ctrl1 - prob_3_ctrl1

## Probability ctrl column 2

prob_2to3_ctrl2 <- inv_logit(logodds1_ctrl2)
prob_3_ctrl2 <- inv_logit(logodds2_ctrl2)
prob_1_ctrl2 <- 1 - prob_2to3_ctrl2
prob_2_ctrl2 <- prob_2to3_ctrl2 - prob_3_ctrl2
  

#generate random outcomes




outcomes_trt1 <- c()
for (i in 1:n_count) {
  outcomes_trt1[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_trt1[i], prob_2_trt1[i], prob_3_trt1[i])
  )
}

outcomes_trt2 <- c()
for (i in 1:n_count) {
  outcomes_trt2[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_trt2[i], prob_2_trt2[i], prob_3_trt2[i])
  )
}



outcomes_ctrl1 <- c()
for (i in 1:n_count) {
  outcomes_ctrl1[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_ctrl1[i], prob_2_ctrl1[i], prob_3_ctrl1[i])
  )
}

outcomes_ctrl2 <- c()
for (i in 1:n_count) {
  outcomes_ctrl2[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_ctrl2[i], prob_2_ctrl2[i], prob_3_ctrl2[i])
  )
}



############################True Win Ratio##############################

# ctrl but assigned in trt group


## trt column 1

logodds1_trt1_assigned <- b01 + as.matrix(ctrl_cov) %*% as.matrix(bi_trt1) + trt_eff1
logodds2_trt1_assigned <- b02 + as.matrix(ctrl_cov) %*% as.matrix(bi_trt1) + trt_eff1


## Probability trt column 1

prob_2to3_trt1_assigned <- inv_logit(logodds1_trt1_assigned)
prob_3_trt1_assigned <- inv_logit(logodds2_trt1_assigned)
prob_1_trt1_assigned <- 1 - prob_2to3_trt1_assigned
prob_2_trt1_assigned <- prob_2to3_trt1_assigned - prob_3_trt1_assigned



## trt column 2

logodds1_trt2_assigned <- b01 + as.matrix(ctrl_cov) %*% as.matrix(bi_trt2) + trt_eff2
logodds2_trt2_assigned <- b02 + as.matrix(ctrl_cov) %*% as.matrix(bi_trt2) + trt_eff2


## Probability trt column 2

prob_2to3_trt2_assigned <- inv_logit(logodds1_trt2_assigned)
prob_3_trt2_assigned <- inv_logit(logodds2_trt2_assigned)
prob_1_trt2_assigned <- 1 - prob_2to3_trt2_assigned
prob_2_trt2_assigned <- prob_2to3_trt2_assigned - prob_3_trt2_assigned








# trt but assigned in ctrl group

## ctrl column 1

logodds1_ctrl1_assigned <- b01 + as.matrix(trt_cov) %*% as.matrix(bi_ctrl1)
logodds2_ctrl1_assigned <- b02 + as.matrix(trt_cov) %*% as.matrix(bi_ctrl1)

## Probability ctrl column 1

prob_2to3_ctrl1_assigned <- inv_logit(logodds1_ctrl1_assigned)
prob_3_ctrl1_assigned <- inv_logit(logodds2_ctrl1_assigned)
prob_1_ctrl1_assigned <- 1 - prob_2to3_ctrl1_assigned
prob_2_ctrl1_assigned <- prob_2to3_ctrl1_assigned - prob_3_ctrl1_assigned


## ctrl column 2

logodds1_ctrl2_assigned <- b01 + as.matrix(trt_cov) %*% as.matrix(bi_ctrl2)
logodds2_ctrl2_assigned <- b02 + as.matrix(trt_cov) %*% as.matrix(bi_ctrl2)

## Probability ctrl column 1

prob_2to3_ctrl2_assigned <- inv_logit(logodds1_ctrl2_assigned)
prob_3_ctrl2_assigned <- inv_logit(logodds2_ctrl2_assigned)
prob_1_ctrl2_assigned <- 1 - prob_2to3_ctrl2_assigned
prob_2_ctrl2_assigned <- prob_2to3_ctrl2_assigned - prob_3_ctrl2_assigned




## outcomes
outcomes_trt1_assigned <- c()
for (i in 1:n_count) {
  outcomes_trt1_assigned[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_trt1_assigned[i], prob_2_trt1_assigned[i], prob_3_trt1_assigned[i])
  )
}

outcomes_trt2_assigned <- c()
for (i in 1:n_count) {
  outcomes_trt2_assigned[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_trt2_assigned[i], prob_2_trt2_assigned[i], prob_3_trt2_assigned[i])
  )
}


outcomes_ctrl1_assigned <- c()
for (i in 1:n_count) {
  outcomes_ctrl1_assigned[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_ctrl1_assigned[i], prob_2_ctrl1_assigned[i], prob_3_ctrl1_assigned[i])
  )
}


outcomes_ctrl2_assigned <- c()
for (i in 1:n_count) {
  outcomes_ctrl2_assigned[i] <- sample(
    outcomes_3lvl, 
    size = 1,
    prob = c(prob_1_ctrl2_assigned[i], prob_2_ctrl2_assigned[i], prob_3_ctrl2_assigned[i])
  )
}


df_trt_true <- data.frame(c(outcomes_trt1, outcomes_trt1_assigned), 
                          c(outcomes_trt2, outcomes_trt2_assigned))
df_ctrl_true <- data.frame(c(outcomes_ctrl1, outcomes_ctrl1_assigned),
                           c(outcomes_ctrl2, outcomes_ctrl2_assigned))

trtwin_true <- matrix(NA, nrow = nrow(df_trt_true), ncol = nrow(df_ctrl_true))
ctrlwin_true <- matrix(NA, nrow = nrow(df_trt_true), ncol = nrow(df_ctrl_true))

for (i in 1:nrow(df_trt_true)){
  for(j in 1:nrow(df_ctrl_true)){

      if (df_trt_true[i,1] > df_ctrl_true[j,1]){
        trtwin_true[i,j] = 1
        ctrlwin_true[i,j] = 0
      }
      else if (df_trt_true[i,1] < df_ctrl_true[j,1]){
        trtwin_true[i,j] = 0
        ctrlwin_true[i,j] = 1
      }
      else if (df_trt_true[i,2] > df_ctrl_true[j,2]) {
        trtwin_true[i,j] = 1
        ctrlwin_true[i,j] = 0
      }
      else if (df_trt_true[i,2] < df_ctrl_true[j,2]) {
        trtwin_true[i,j] = 0
        ctrlwin_true[i,j] = 1
      }

  }
}


trt_winpr_true <- sum(as.vector(trtwin_true), 
                      na.rm = T)/(nrow(df_trt_true)*nrow(df_ctrl_true))
ctrl_winpr_true <- sum(as.vector(ctrlwin_true), 
                       na.rm = T)/(nrow(df_trt_true)*nrow(df_ctrl_true))




WR_sim_trueWR[sim_count] <- trt_winpr_true/ctrl_winpr_true









##############Original Estimator##########################

df_trt_comp <- data.frame(outcomes_trt1, outcomes_trt2)
df_ctrl_comp <- data.frame(outcomes_ctrl1, outcomes_ctrl2)

trtwin_comp <- matrix(NA, nrow = nrow(df_trt_comp), ncol = nrow(df_ctrl_comp))
ctrlwin_comp <- matrix(NA, nrow = nrow(df_trt_comp), ncol = nrow(df_ctrl_comp))

for (i in 1:nrow(df_trt_comp)){
  for(j in 1:nrow(df_ctrl_comp)){

      if (df_trt_comp[i,1] > df_ctrl_comp[j,1]){
        trtwin_comp[i,j] = 1
        ctrlwin_comp[i,j] = 0
      }
      else if (df_trt_comp[i,1] < df_ctrl_comp[j,1]){
        trtwin_comp[i,j] = 0
        ctrlwin_comp[i,j] = 1
      }
      else if (df_trt_comp[i,2] > df_ctrl_comp[j,2]) {
        trtwin_comp[i,j] = 1
        ctrlwin_comp[i,j] = 0
      }
      else if (df_trt_comp[i,2] < df_ctrl_comp[j,2]) {
        trtwin_comp[i,j] = 0
        ctrlwin_comp[i,j] = 1
      }
    
    

  }
}


trt_winpr_comp <- sum(as.vector(trtwin_comp), 
                      na.rm = T)/(nrow(df_trt_comp)*nrow(df_ctrl_comp))
ctrl_winpr_comp <- sum(as.vector(ctrlwin_comp), 
                       na.rm = T)/(nrow(df_trt_comp)*nrow(df_ctrl_comp))

WR_sim_comp[sim_count] <- trt_winpr_comp/ctrl_winpr_comp





##############IPS-Weighted########################################




colnames(df_trt_comp) <- c("outcomes_comb1", "outcomes_comb2")
colnames(df_ctrl_comp) <- c("outcomes_comb1", "outcomes_comb2")

df_comb <- rbind(df_trt_comp, df_ctrl_comp)
df_comb$treatment <- c(rep(1,n_count), rep(0,n_count))
df_comb$x1 <- c(x1_trt, x1_ctrl)
df_comb$x2 <- c(x2_trt, x2_ctrl)
df_comb$x3 <- c(x3_trt, x3_ctrl)
df_comb$x4 <- c(x4_trt, x4_ctrl)
df_comb$x5 <- c(x5_trt, x5_ctrl)
df_comb$x6 <- c(x6_trt, x6_ctrl)

###PS
PropScore <- glm(treatment~x1 + x2 + x3 + x4 + x5 + x6, 
                 data = df_comb, family=binomial)
pi_func <- fitted(PropScore)

g_hfunc_IPS1 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_ctrl_comp))
g_hfunc_IPS2 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_ctrl_comp))

for (i in 1:(2*n_count-1)){
  for(j in (i+1):(2*n_count)){

      if (df_comb[i,1] > df_comb[j,1]){
        g_hfunc_IPS1[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))
        g_hfunc_IPS2[i,j] = 0
      }
      else if (df_comb[i,1] < df_comb[j,1]){
        g_hfunc_IPS1[i,j] = 0
        g_hfunc_IPS2[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))
      }
      else if (df_comb[i,2] > df_comb[j,2]){
        g_hfunc_IPS1[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))
        g_hfunc_IPS2[i,j] = 0
      }
      else if (df_comb[i,2] < df_comb[j,2]){
        g_hfunc_IPS1[i,j] = 0
        g_hfunc_IPS2[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))
      }

  }
}



tau1_IPS <- sum(as.vector(g_hfunc_IPS1), na.rm = T)/(choose(2*n_count,2))
tau2_IPS <- sum(as.vector(g_hfunc_IPS2), na.rm = T)/(choose(2*n_count,2))



WR_sim_comp_IPS[sim_count] <- tau1_IPS/tau2_IPS









######################Overlap Weighting##############################


g_hfunc_OW1 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_ctrl_comp))
g_hfunc_OW2 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_ctrl_comp))

for (i in 1:(2*n_count-1)){
  for(j in (i+1):(2*n_count)){

      if (df_comb[i,1] > df_comb[j,1]){
        g_hfunc_OW1[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])
        g_hfunc_OW2[i,j] = 0
      }
      else if (df_comb[i,1] < df_comb[j,1]){
        g_hfunc_OW1[i,j] = 0
        g_hfunc_OW2[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])
      }
      else if (df_comb[i,2] > df_comb[j,2]){
        g_hfunc_OW1[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])
        g_hfunc_OW2[i,j] = 0
      }
      else if (df_comb[i,2] < df_comb[j,2]){
        g_hfunc_OW1[i,j] = 0
        g_hfunc_OW2[i,j] = (0.5)*(df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])
      }

  }
}


tau1_OW <- sum(as.vector(g_hfunc_OW1), na.rm = T)/(choose(2*n_count,2))
tau2_OW <- sum(as.vector(g_hfunc_OW2), na.rm = T)/(choose(2*n_count,2))



WR_sim_comp_OW[sim_count] <- tau1_OW/tau2_OW




###############Doubly Robust Estimator################################


###DR mu-function

if((!(1 %in% df_comb[df_comb$treatment==1,]$outcomes_comb1) &
     !(2 %in% df_comb[df_comb$treatment==1,]$outcomes_comb1)) |
     (!(1 %in% df_comb[df_comb$treatment==0,]$outcomes_comb1) &
     !(2 %in% df_comb[df_comb$treatment==0,]$outcomes_comb1)) |
     (!(1 %in% df_comb[df_comb$treatment==1,]$outcomes_comb2) &
     !(2 %in% df_comb[df_comb$treatment==1,]$outcomes_comb2)) |
     (!(1 %in% df_comb[df_comb$treatment==0,]$outcomes_comb2) &
     !(2 %in% df_comb[df_comb$treatment==0,]$outcomes_comb2))){
  break
}

else {
dr_trt1 <- vglm(factor(outcomes_comb1) ~ x1 + x2 + x3 + x4 + x5 + x6, 
                data = df_comb[df_comb$treatment==1,], 
                family = multinomial)
dr_trt2 <- vglm(factor(outcomes_comb2) ~ x1 + x2 + x3 + x4 + x5 + x6, 
                data = df_comb[df_comb$treatment==1,], 
                family = multinomial)
dr_ctrl1 <- vglm(factor(outcomes_comb1) ~ x1 + x2 + x3 + x4 + x5 + x6, 
                data = df_comb[df_comb$treatment==0,], 
                family = multinomial)
dr_ctrl2 <- vglm(factor(outcomes_comb2) ~ x1 + x2 + x3 + x4 + x5 + x6, 
                data = df_comb[df_comb$treatment==0,], 
                family = multinomial)

cond_prob_trt1 <- predictvglm(dr_trt1, newdata = df_comb,
                              type = "response")
cond_prob_trt2 <- predictvglm(dr_trt2, newdata = df_comb, 
                              type = "response")
cond_prob_ctrl1 <- predictvglm(dr_ctrl1, newdata = df_comb, 
                               type = "response")
cond_prob_ctrl2 <- predictvglm(dr_ctrl2, newdata = df_comb, 
                               type = "response")
}

prob1_0 <-data.frame(rep(0,n_count))
colnames(prob1_0) <- "1"
prob2_0 <-data.frame(rep(0,n_count))
colnames(prob2_0) <- "2"





if(!"1" %in% colnames(cond_prob_trt1)){
  cond_prob_trt1 <- cbind(prob1_0, cond_prob_trt1)
}

if(!"1" %in% colnames(cond_prob_ctrl1)){
  cond_prob_ctrl1 <- cbind(prob1_0, cond_prob_ctrl1)
}
if(!"2" %in% colnames(cond_prob_trt1)){
  col1 <- data.frame(cond_prob_trt1[,1])
  colnames(col1) <- "1"
  col3 <- data.frame(cond_prob_trt1[,2])
  colnames(col3) <- "3"
  cond_prob_trt1 <- cbind(col1, prob2_0, col3)
}

if(!"2" %in% colnames(cond_prob_ctrl1)){
  col1 <- data.frame(cond_prob_ctrl1[,1])
  colnames(col1) <- "1"
  col3 <- data.frame(cond_prob_ctrl1[,2])
  colnames(col3) <- "3"
  cond_prob_ctrl1 <- cbind(col1, prob2_0, col3)
}




if(!"1" %in% colnames(cond_prob_trt2)){
  cond_prob_trt2 <- cbind(prob1_0, cond_prob_trt2)
}

if(!"1" %in% colnames(cond_prob_ctrl2)){
  cond_prob_ctrl2 <- cbind(prob1_0, cond_prob_ctrl2)
}
if(!"2" %in% colnames(cond_prob_trt2)){
  col1 <- data.frame(cond_prob_trt2[,1])
  colnames(col1) <- "1"
  col3 <- data.frame(cond_prob_trt2[,2])
  colnames(col3) <- "3"
  cond_prob_trt2 <- cbind(col1, prob2_0, col3)
}

if(!"2" %in% colnames(cond_prob_ctrl2)){
  col1 <- data.frame(cond_prob_ctrl2[,1])
  colnames(col1) <- "1"
  col3 <- data.frame(cond_prob_ctrl2[,2])
  colnames(col3) <- "3"
  cond_prob_ctrl2 <- cbind(col1, prob2_0, col3)
}


#cond_prob1 <- rbind(cond_prob_trt1, cond_prob_ctrl1)
#cond_prob2 <- rbind(cond_prob_trt2, cond_prob_ctrl2)

g_hfunc_DR1 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_ctrl_comp))
g_hfunc_DR2 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_ctrl_comp))





for (i in 1:(2*n_count-1)){
  for(j in (i+1):(2*n_count)){

      if (df_comb[i,1] > df_comb[j,1]){
        g_hfunc_DR1[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        

        g_hfunc_DR2[i,j] = (0.5)*(0 - 
                               (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            ) +
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1/(pi_func[j]*(1-pi_func[i])))-
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
      }
      else if (df_comb[i,1] < df_comb[j,1]){
        g_hfunc_DR1[i,j] = (0.5)*(0 -
                              (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) +
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1/(pi_func[j]*(1-pi_func[i])))-
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        
        g_hfunc_DR2[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            )
                                            + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
      }
      else if (df_comb[i,2] > df_comb[j,2]){
        
        g_hfunc_DR1[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        

        g_hfunc_DR2[i,j] = (0.5)*(0 - 
                               (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            ) +
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1/(pi_func[j]*(1-pi_func[i])))-
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
        
        
      }
    
      else if (df_comb[i,2] < df_comb[j,2]){
        g_hfunc_DR1[i,j] = (0.5)*(0 -
                              (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) +
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1/(pi_func[j]*(1-pi_func[i])))-
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        
        g_hfunc_DR2[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1/(pi_func[i]*(1-pi_func[j])))-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])/(pi_func[i]*(1-pi_func[j]))-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            )
                                            + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])/(pi_func[j]*(1-pi_func[i]))-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
        
      }

  }
}

    

tau1_DR <- sum(as.vector(g_hfunc_DR1), na.rm = T) / (choose(2*n_count, 2))
tau2_DR <- sum(as.vector(g_hfunc_DR2), na.rm = T) / (choose(2*n_count, 2))

WR_sim_comp_DR[sim_count] <- tau1_DR/tau2_DR







################Doubly Robust with Overlap Weighting######################

g_hfunc_DROW1 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_trt_comp))
g_hfunc_DROW2 <- matrix(0, nrow = 2*nrow(df_trt_comp), ncol = 2*nrow(df_trt_comp))



for (i in 1:(2*n_count-1)){
  for(j in (i+1):(2*n_count)){

      if (df_comb[i,1] > df_comb[j,1]){
        g_hfunc_DROW1[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        

        g_hfunc_DROW2[i,j] = (0.5)*(0 - 
                               (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            ) +
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1*(1-pi_func[j])*pi_func[i])-
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
      }
      else if (df_comb[i,1] < df_comb[j,1]){
        g_hfunc_DROW1[i,j] = (0.5)*(0 -
                              (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) +
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1*(1-pi_func[j])*pi_func[i])-
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        
        g_hfunc_DROW2[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            )
                                            + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
      }
      else if (df_comb[i,2] > df_comb[j,2]){
        
        g_hfunc_DROW1[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        

        g_hfunc_DROW2[i,j] = (0.5)*(0 - 
                               (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            ) +
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1*(1-pi_func[j])*pi_func[i])-
                                 (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
        
        
      }
    
      else if (df_comb[i,2] < df_comb[j,2]){
        g_hfunc_DROW1[i,j] = (0.5)*(0 -
                              (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,2]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,2]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,1]+
                                            cond_prob_trt2[i,3]*cond_prob_ctrl2[j,2]
                                            )
                                            ) +
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*1*(1-pi_func[j])*pi_func[i])-
                                (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,2]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,2]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,1]+
                                            cond_prob_trt2[j,3]*cond_prob_ctrl2[i,2]
                                            ))
                                            )
        
        g_hfunc_DROW2[i,j] = (0.5)*((df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*1*(1-pi_func[i])*pi_func[j])-
                                  (df_comb[i,"treatment"]*(1-df_comb[j,"treatment"])*(1-pi_func[i])*pi_func[j]-1)*
                                           (cond_prob_trt1[i,1]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,3]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,3]+
                                            (
                                            cond_prob_trt1[i,1]*cond_prob_ctrl1[j,1]+
                                            cond_prob_trt1[i,2]*cond_prob_ctrl1[j,2]+
                                            cond_prob_trt1[i,3]*cond_prob_ctrl1[j,3]
                                            )*(
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,2]+
                                            cond_prob_trt2[i,1]*cond_prob_ctrl2[j,3]+
                                            cond_prob_trt2[i,2]*cond_prob_ctrl2[j,3]
                                            )
                                            )
                                            + 0 -
                                    (df_comb[j,"treatment"]*(1-df_comb[i,"treatment"])*(1-pi_func[j])*pi_func[i]-1)*
                                           (cond_prob_trt1[j,1]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,3]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,3]+
                                            (
                                            cond_prob_trt1[j,1]*cond_prob_ctrl1[i,1]+
                                            cond_prob_trt1[j,2]*cond_prob_ctrl1[i,2]+
                                            cond_prob_trt1[j,3]*cond_prob_ctrl1[i,3]
                                            )*(
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,2]+
                                            cond_prob_trt2[j,1]*cond_prob_ctrl2[i,3]+
                                            cond_prob_trt2[j,2]*cond_prob_ctrl2[i,3]
                                            )
                                            )
                                            )
        
      }

  }
}

tau1_DROW <- sum(as.vector(g_hfunc_DROW1), na.rm = T) / (choose(2*n_count, 2))
tau2_DROW <- sum(as.vector(g_hfunc_DROW2), na.rm = T) / (choose(2*n_count, 2))

WR_sim_comp_DROW[sim_count] <- tau1_DROW/tau2_DROW

}




#################Original Estimator Output#########################

bias_Ori <- WR_sim_comp - WR_sim_trueWR


WR_sim_noninf_comp <- WR_sim_comp[WR_sim_comp!=Inf &
                                  WR_sim_comp!=0 &
                                  !is.na(WR_sim_comp)]


empirical_var_Ori[count_temp] <- var(WR_sim_noninf_comp)
avg_bias_Ori[count_temp] <- mean(bias_Ori)
mse_Ori[count_temp] <- avg_bias_Ori[count_temp]^2 + empirical_var_Ori[count_temp]







###############IPS Estimator Output###########################

bias_IPS <- WR_sim_comp_IPS - WR_sim_trueWR

WR_sim_noninf_comp_IPS <- WR_sim_comp_IPS[WR_sim_comp_IPS!=Inf &
                                  WR_sim_comp_IPS!=0 &
                                  !is.na(WR_sim_comp_IPS)]


empirical_var_IPS[count_temp] <- var(WR_sim_noninf_comp_IPS)
avg_bias_IPS[count_temp] <- mean(bias_IPS)
mse_IPS[count_temp] <- avg_bias_IPS[count_temp]^2 + empirical_var_IPS[count_temp]



###############OW Estimator Output###########################

bias_OW <- WR_sim_comp_OW - WR_sim_trueWR

WR_sim_noninf_comp_OW <- WR_sim_comp_OW[WR_sim_comp_OW!=Inf &
                                  WR_sim_comp_OW!=0 &
                                  !is.na(WR_sim_comp_OW)]


empirical_var_OW[count_temp] <- var(WR_sim_noninf_comp_OW)
avg_bias_OW[count_temp] <- mean(bias_OW)
mse_OW[count_temp] <- avg_bias_OW[count_temp]^2 + empirical_var_OW[count_temp]



###############Doubly Robust Estimator Output#####################

bias_DR <- WR_sim_comp_DR - WR_sim_trueWR


WR_sim_noninf_comp_DR <- WR_sim_comp_DR[WR_sim_comp_DR!=Inf & 
                                        WR_sim_comp_DR!=0 & 
                                        !is.na(WR_sim_comp_DR)]

empirical_var_DR[count_temp] <- var(WR_sim_noninf_comp_DR)
avg_bias_DR[count_temp] <- mean(bias_DR)
mse_DR[count_temp] <- avg_bias_DR[count_temp]^2 + empirical_var_DR[count_temp]



###############Doubly Robust OW Estimator Output#####################

bias_DROW <- WR_sim_comp_DROW - WR_sim_trueWR


WR_sim_noninf_comp_DROW <- WR_sim_comp_DROW[WR_sim_comp_DROW!=Inf & 
                                        WR_sim_comp_DROW!=0 & 
                                        !is.na(WR_sim_comp_DROW)]

empirical_var_DROW[count_temp] <- var(WR_sim_noninf_comp_DROW)
avg_bias_DROW[count_temp] <- mean(bias_DROW)
mse_DROW[count_temp] <- avg_bias_DROW[count_temp]^2 + empirical_var_DROW[count_temp]



}




relative_eff_IPS <- empirical_var_Ori/empirical_var_IPS
relative_eff_OW <- empirical_var_Ori/empirical_var_OW
relative_eff_DR <- empirical_var_Ori/empirical_var_DR
relative_eff_DROW <- empirical_var_Ori/empirical_var_DROW






save(re_count, step_size, relative_eff_IPS, relative_eff_OW,
     relative_eff_DR, relative_eff_DROW,
     empirical_var_Ori, avg_bias_Ori, mse_Ori,
     empirical_var_IPS, avg_bias_IPS, mse_IPS,
     empirical_var_OW, avg_bias_OW, mse_OW,
     empirical_var_DR, avg_bias_DR, mse_DR,
     empirical_var_DROW, avg_bias_DROW, mse_DROW,
     file = "Integrated_Output_CompAddCov.RData")
```






## Relative Efficiency Visulization



```{r, warning=FALSE}
library(ggplot2)




var_Ori_df <- data.frame(empirical_var_Ori)
var_IPS_df <- data.frame(empirical_var_IPS)
var_OW_df <- data.frame(empirical_var_OW)
var_DR_df <- data.frame(empirical_var_DR)
var_DROW_df <- data.frame(empirical_var_DROW)


colnames(var_Ori_df) <- "variance"
colnames(var_IPS_df) <- "variance"
colnames(var_OW_df) <- "variance"
colnames(var_DR_df) <- "variance"
colnames(var_DROW_df) <- "variance"

sim_df <- rbind(var_Ori_df, var_IPS_df, var_OW_df, var_DR_df, var_DROW_df)
sim_df$mse <- c(mse_Ori, mse_IPS, mse_OW, mse_DR, mse_DROW)
sim_df$bias <- c(avg_bias_Ori, avg_bias_IPS, avg_bias_OW, avg_bias_DR, avg_bias_DROW)

sim_df$estimator <- c(rep("original",re_count), rep("IPS",re_count),
                      rep("OW",re_count), rep("DR",re_count), rep("DROW",re_count))
sim_df$estimator <- as.factor(sim_df$estimator)
sim_df$samplesize <- c(c(1:re_count)*step_size, c(1:re_count)*step_size, c(1:re_count)*step_size,
                       c(1:re_count)*step_size, c(1:re_count)*step_size)

sim_df <- sim_df[is.finite(rowSums(cbind(sim_df$variance, 
                                         sim_df$mse,
                                         sim_df$bias))), ]




var_plot <- ggplot(sim_df, aes(x=samplesize, y = variance,
                                  color = estimator)) + 
  geom_point() + 
  geom_line(aes(group = estimator)) + 
  scale_color_manual(values = c("original" = "black", "IPS" = "gold",
                                "OW" = "orange", "DR" = "red", 
                                "DROW" = "brown")) +
  ggtitle("Variance comparison from Simulation") +
  xlab("Sample Size") + ylab("Variance") +
  scale_x_continuous(breaks=seq(0,step_size*re_count,step_size)) + 
  theme(
    plot.title = element_text(color="red", size=12, face="bold.italic"),
    axis.title.x = element_text(size=12),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size=12),
    legend.text = element_text(size=12)
    )



var_plot


mse_plot <- ggplot(sim_df, aes(x=samplesize, y = mse,
                                  color = estimator)) + 
  geom_point() + 
  geom_line(aes(group = estimator)) + 
  scale_color_manual(values = c("original" = "black", "IPS" = "gold",
                                "OW" = "orange", "DR" = "red",
                                "DROW" = "brown"))+
  ggtitle("MSE comparison from Simulation") +
  xlab("Sample Size") + ylab("MSE") +
  scale_x_continuous(breaks=seq(0,step_size*re_count,step_size)) + 
  theme(
    plot.title = element_text(color="red", size=12, face="bold.italic"),
    axis.title.x = element_text(size=12),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size=12),
    legend.text = element_text(size=12)
    )


mse_plot


bias_plot <- ggplot(sim_df, aes(x = samplesize, y = bias,
                                  color = estimator)) + 
  geom_point() + 
  geom_line(aes(group = estimator)) +
  scale_color_manual(values = c("original" = "black", "IPS" = "gold",
                                "OW" = "orange", "DR" = "red",
                                "DROW" = "brown")) +
  ggtitle("Win Ratio Bias from Simulation") +
  xlab("Sample Size") + ylab("Bias") +
  scale_x_continuous(breaks=seq(0,step_size*re_count,step_size)) +
  theme(
    plot.title = element_text(color="red", size=12, face="bold.italic"),
    axis.title.x = element_text(size=12),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size=12),
    legend.text = element_text(size=12)
  )



bias_plot




re_df <- data.frame(c(relative_eff_IPS, relative_eff_OW, 
                      relative_eff_DR, relative_eff_DROW))
colnames(re_df) <- "relative_eff"
re_df$samplesize <- c(c(1:re_count)*step_size, c(1:re_count)*step_size, 
                      c(1:re_count)*step_size, c(1:re_count)*step_size)
re_df$estimator <- c(rep("IPS",re_count), rep("OW",re_count), 
                     rep("DR",re_count), rep("DROW",re_count))
re_df$estimator <- as.factor(re_df$estimator)


re_plot <- ggplot(re_df, aes(x=samplesize, y = relative_eff,
                             color = estimator)) + 
  geom_point() + 
  geom_line(aes(group = estimator)) +
  scale_color_manual(values = c("IPS" = "gold", "OW" = "orange", 
                                "DR" = "red", "DROW" = "brown")) +
  geom_hline(yintercept=1, linetype="dashed", color = "red") +
  ggtitle("Relative Efficiency from Simulation") +
  xlab("Sample Size") + ylab("Relative Efficiency") +
  scale_x_continuous(breaks=seq(0,step_size*re_count,step_size)) +
  theme(
    plot.title = element_text(color="red", size=12, face="bold.italic"),
    axis.title.x = element_text(size=12),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size=12),
    legend.text = element_text(size=12)
    )



re_plot

```

















## Run Time


```{r}
end_time <- Sys.time()

run_time <- end_time - start_time

run_time
```




















